# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 861)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:  #142850;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.column = QtWidgets.QTabWidget(self.centralwidget)
        self.column.setAutoFillBackground(False)
        self.column.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"color:  #00a8cc;\n"
"background-color: #27496d;\n"
"")
        self.column.setObjectName("column")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_mainTable = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget_mainTable.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(173, 173, 173);")
        self.tableWidget_mainTable.setRowCount(10)
        self.tableWidget_mainTable.setObjectName("tableWidget_mainTable")
        self.tableWidget_mainTable.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_mainTable.setHorizontalHeaderItem(6, item)
        self.tableWidget_mainTable.horizontalHeader().setDefaultSectionSize(144)
        self.gridLayout_3.addWidget(self.tableWidget_mainTable, 2, 1, 1, 1)
        self.pushButton_mainStartAll = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mainStartAll.sizePolicy().hasHeightForWidth())
        self.pushButton_mainStartAll.setSizePolicy(sizePolicy)
        self.pushButton_mainStartAll.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_mainStartAll.setObjectName("pushButton_mainStartAll")
        self.gridLayout_3.addWidget(self.pushButton_mainStartAll, 4, 1, 1, 1)
        self.pushButton_updateMainTable = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_updateMainTable.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_updateMainTable.setObjectName("pushButton_updateMainTable")
        self.gridLayout_3.addWidget(self.pushButton_updateMainTable, 1, 1, 1, 1)
        self.pushButton_mainStart = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mainStart.sizePolicy().hasHeightForWidth())
        self.pushButton_mainStart.setSizePolicy(sizePolicy)
        self.pushButton_mainStart.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_mainStart.setObjectName("pushButton_mainStart")
        self.gridLayout_3.addWidget(self.pushButton_mainStart, 3, 1, 1, 1)
        self.lineEdit_time_duration = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_time_duration.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_time_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time_duration.setObjectName("lineEdit_time_duration")
        self.gridLayout_3.addWidget(self.lineEdit_time_duration, 0, 1, 1, 1)
        self.pushButton_mainStop = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mainStop.sizePolicy().hasHeightForWidth())
        self.pushButton_mainStop.setSizePolicy(sizePolicy)
        self.pushButton_mainStop.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(152, 0, 0);")
        self.pushButton_mainStop.setObjectName("pushButton_mainStop")
        self.gridLayout_3.addWidget(self.pushButton_mainStop, 6, 1, 1, 1)
        self.pushButton_stop_all = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_stop_all.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(152, 0, 0);")
        self.pushButton_stop_all.setObjectName("pushButton_stop_all")
        self.gridLayout_3.addWidget(self.pushButton_stop_all, 7, 1, 1, 1)
        self.column.addTab(self.tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_accUsername = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_accUsername.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_accUsername.setObjectName("lineEdit_accUsername")
        self.gridLayout_4.addWidget(self.lineEdit_accUsername, 1, 3, 1, 1)
        self.lineEdit_accPlaylist = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_accPlaylist.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_accPlaylist.setObjectName("lineEdit_accPlaylist")
        self.gridLayout_4.addWidget(self.lineEdit_accPlaylist, 3, 3, 1, 1)
        self.pushButton_account_add_db = QtWidgets.QPushButton(self.tab)
        self.pushButton_account_add_db.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_account_add_db.setObjectName("pushButton_account_add_db")
        self.gridLayout_4.addWidget(self.pushButton_account_add_db, 5, 3, 1, 1)
        self.lineEdit_accPass = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_accPass.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_accPass.setObjectName("lineEdit_accPass")
        self.gridLayout_4.addWidget(self.lineEdit_accPass, 2, 3, 1, 1)
        self.lineEdit_accId = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_accId.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_accId.setObjectName("lineEdit_accId")
        self.gridLayout_4.addWidget(self.lineEdit_accId, 6, 3, 1, 1)
        self.pushButton_account_refresh_table = QtWidgets.QPushButton(self.tab)
        self.pushButton_account_refresh_table.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_account_refresh_table.setObjectName("pushButton_account_refresh_table")
        self.gridLayout_4.addWidget(self.pushButton_account_refresh_table, 10, 1, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 6, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 2, 1, 1)
        self.pushButton_accRemFromDb = QtWidgets.QPushButton(self.tab)
        self.pushButton_accRemFromDb.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(152, 0, 0);")
        self.pushButton_accRemFromDb.setObjectName("pushButton_accRemFromDb")
        self.gridLayout_4.addWidget(self.pushButton_accRemFromDb, 8, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 2, 1, 1)
        self.tableWidget_accTable = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_accTable.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(173, 173, 173);")
        self.tableWidget_accTable.setRowCount(3)
        self.tableWidget_accTable.setObjectName("tableWidget_accTable")
        self.tableWidget_accTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_accTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_accTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_accTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_accTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_accTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_accTable.setHorizontalHeaderItem(5, item)
        self.tableWidget_accTable.horizontalHeader().setDefaultSectionSize(171)
        self.gridLayout_4.addWidget(self.tableWidget_accTable, 9, 1, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 2, 1, 1)
        self.lineEdit_proxy_ip = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_proxy_ip.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_proxy_ip.setObjectName("lineEdit_proxy_ip")
        self.gridLayout_4.addWidget(self.lineEdit_proxy_ip, 4, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 2, 1, 1)
        self.column.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_songsRemFromDb = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_songsRemFromDb.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(152, 0, 0);")
        self.pushButton_songsRemFromDb.setObjectName("pushButton_songsRemFromDb")
        self.gridLayout.addWidget(self.pushButton_songsRemFromDb, 7, 1, 1, 1)
        self.lineEdit_songsPlaylist = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_songsPlaylist.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_songsPlaylist.setObjectName("lineEdit_songsPlaylist")
        self.gridLayout.addWidget(self.lineEdit_songsPlaylist, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.pushButton_songsRefreshTable = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_songsRefreshTable.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_songsRefreshTable.setObjectName("pushButton_songsRefreshTable")
        self.gridLayout.addWidget(self.pushButton_songsRefreshTable, 9, 0, 1, 2)
        self.pushButton_songsAddToDb = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_songsAddToDb.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_songsAddToDb.setObjectName("pushButton_songsAddToDb")
        self.gridLayout.addWidget(self.pushButton_songsAddToDb, 5, 1, 1, 1)
        self.lineEdit_songsName = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_songsName.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_songsName.setObjectName("lineEdit_songsName")
        self.gridLayout.addWidget(self.lineEdit_songsName, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_songsLink = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_songsLink.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_songsLink.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_songsLink.setObjectName("lineEdit_songsLink")
        self.gridLayout.addWidget(self.lineEdit_songsLink, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_songsId = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_songsId.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_songsId.setObjectName("lineEdit_songsId")
        self.gridLayout.addWidget(self.lineEdit_songsId, 6, 1, 1, 1)
        self.tableWidget_songsTable = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_songsTable.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(173, 173, 173);\n"
"\n"
"")
        self.tableWidget_songsTable.setRowCount(3)
        self.tableWidget_songsTable.setObjectName("tableWidget_songsTable")
        self.tableWidget_songsTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_songsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_songsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_songsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_songsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_songsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_songsTable.setHorizontalHeaderItem(5, item)
        self.tableWidget_songsTable.horizontalHeader().setDefaultSectionSize(171)
        self.gridLayout.addWidget(self.tableWidget_songsTable, 8, 0, 1, 2)
        self.column.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_viewPlayListTable = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_viewPlayListTable.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(173, 173, 173);\n"
"\n"
"")
        self.tableWidget_viewPlayListTable.setRowCount(3)
        self.tableWidget_viewPlayListTable.setObjectName("tableWidget_viewPlayListTable")
        self.tableWidget_viewPlayListTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_viewPlayListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_viewPlayListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_viewPlayListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_viewPlayListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_viewPlayListTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_viewPlayListTable.setHorizontalHeaderItem(5, item)
        self.tableWidget_viewPlayListTable.horizontalHeader().setDefaultSectionSize(171)
        self.gridLayout_6.addWidget(self.tableWidget_viewPlayListTable, 1, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_viewShowPlaylist = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_viewShowPlaylist.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_viewShowPlaylist.setObjectName("pushButton_viewShowPlaylist")
        self.gridLayout_6.addWidget(self.pushButton_viewShowPlaylist, 2, 0, 1, 2)
        self.lineEdit_viewPlaylist = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_viewPlaylist.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_viewPlaylist.setObjectName("lineEdit_viewPlaylist")
        self.gridLayout_6.addWidget(self.lineEdit_viewPlaylist, 0, 1, 1, 1)
        self.column.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_spotify = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_spotify.sizePolicy().hasHeightForWidth())
        self.radioButton_spotify.setSizePolicy(sizePolicy)
        self.radioButton_spotify.setChecked(True)
        self.radioButton_spotify.setObjectName("radioButton_spotify")
        self.gridLayout_7.addWidget(self.radioButton_spotify, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 5, 0, 1, 1)
        self.lineEdit_proxy_user = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_proxy_user.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_proxy_user.setObjectName("lineEdit_proxy_user")
        self.gridLayout_7.addWidget(self.lineEdit_proxy_user, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 6, 0, 1, 1)
        self.lineEdit_db_port = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_db_port.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_db_port.setObjectName("lineEdit_db_port")
        self.gridLayout_7.addWidget(self.lineEdit_db_port, 4, 1, 1, 1)
        self.lineEdit_db_user = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_db_user.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_db_user.setObjectName("lineEdit_db_user")
        self.gridLayout_7.addWidget(self.lineEdit_db_user, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 8, 0, 1, 1)
        self.lineEdit_proxy_pass = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_proxy_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_proxy_pass.setObjectName("lineEdit_proxy_pass")
        self.gridLayout_7.addWidget(self.lineEdit_proxy_pass, 8, 1, 1, 1)
        self.lineEdit_db_ip = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_db_ip.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_db_ip.setObjectName("lineEdit_db_ip")
        self.gridLayout_7.addWidget(self.lineEdit_db_ip, 3, 1, 1, 1)
        self.pushButton_create_db_table = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_create_db_table.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_create_db_table.setObjectName("pushButton_create_db_table")
        self.gridLayout_7.addWidget(self.pushButton_create_db_table, 10, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.pushButton_create_demo_playlist = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_create_demo_playlist.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"color: rgb(0, 81, 0);")
        self.pushButton_create_demo_playlist.setObjectName("pushButton_create_demo_playlist")
        self.gridLayout_7.addWidget(self.pushButton_create_demo_playlist, 11, 1, 1, 1)
        self.radioButton_tidal = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_tidal.sizePolicy().hasHeightForWidth())
        self.radioButton_tidal.setSizePolicy(sizePolicy)
        self.radioButton_tidal.setObjectName("radioButton_tidal")
        self.gridLayout_7.addWidget(self.radioButton_tidal, 2, 1, 1, 1)
        self.lineEdit_db_pass = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_db_pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_db_pass.setObjectName("lineEdit_db_pass")
        self.gridLayout_7.addWidget(self.lineEdit_db_pass, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 7, 0, 1, 1)
        self.lineEdit_proxy_port = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_proxy_port.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_proxy_port.setObjectName("lineEdit_proxy_port")
        self.gridLayout_7.addWidget(self.lineEdit_proxy_port, 9, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 9, 0, 1, 1)
        self.column.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.column, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.column.setCurrentIndex(0)
        self.pushButton_stop_all.clicked.connect(self.tableWidget_mainTable.clearSelection)
        self.pushButton_mainStartAll.clicked.connect(self.tableWidget_mainTable.selectAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DoDoe Viral"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Playlist"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Proxy IP"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Site"))
        item = self.tableWidget_mainTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        self.pushButton_mainStartAll.setText(_translate("MainWindow", "Start All"))
        self.pushButton_updateMainTable.setText(_translate("MainWindow", "Update Table"))
        self.pushButton_mainStart.setText(_translate("MainWindow", "Start"))
        self.lineEdit_time_duration.setText(_translate("MainWindow", "35"))
        self.pushButton_mainStop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_stop_all.setText(_translate("MainWindow", "Stop All"))
        self.column.setTabText(self.column.indexOf(self.tab_1), _translate("MainWindow", "Main"))
        self.pushButton_account_add_db.setText(_translate("MainWindow", "Add to Database"))
        self.pushButton_account_refresh_table.setText(_translate("MainWindow", "Refresh Table"))
        self.label_12.setText(_translate("MainWindow", "ID"))
        self.label_8.setText(_translate("MainWindow", "Username"))
        self.pushButton_accRemFromDb.setText(_translate("MainWindow", "Remove from Database"))
        self.label_2.setText(_translate("MainWindow", "Playlist"))
        item = self.tableWidget_accTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_accTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_accTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_accTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Playlist"))
        item = self.tableWidget_accTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Proxy IP"))
        item = self.tableWidget_accTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Site"))
        self.label_9.setText(_translate("MainWindow", "Password"))
        self.label_16.setText(_translate("MainWindow", "Proxy IP"))
        self.column.setTabText(self.column.indexOf(self.tab), _translate("MainWindow", "Accounts"))
        self.pushButton_songsRemFromDb.setText(_translate("MainWindow", "Remove from Database"))
        self.label_6.setText(_translate("MainWindow", "Stream Link"))
        self.pushButton_songsRefreshTable.setText(_translate("MainWindow", "Refresh Table"))
        self.pushButton_songsAddToDb.setText(_translate("MainWindow", "Add to Database"))
        self.label_3.setText(_translate("MainWindow", "Playlist"))
        self.label_13.setText(_translate("MainWindow", "ID"))
        self.label_7.setText(_translate("MainWindow", "Song Name"))
        item = self.tableWidget_songsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_songsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count"))
        item = self.tableWidget_songsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Streams"))
        item = self.tableWidget_songsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Song Name"))
        item = self.tableWidget_songsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Playlist"))
        item = self.tableWidget_songsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Site"))
        self.column.setTabText(self.column.indexOf(self.tab_2), _translate("MainWindow", "Songs"))
        item = self.tableWidget_viewPlayListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_viewPlayListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count"))
        item = self.tableWidget_viewPlayListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Streams"))
        item = self.tableWidget_viewPlayListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Songs"))
        item = self.tableWidget_viewPlayListTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Playlist"))
        item = self.tableWidget_viewPlayListTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Site"))
        self.label_4.setText(_translate("MainWindow", "Playlist"))
        self.pushButton_viewShowPlaylist.setText(_translate("MainWindow", "Show Playlist"))
        self.lineEdit_viewPlaylist.setText(_translate("MainWindow", "Demo"))
        self.column.setTabText(self.column.indexOf(self.tab_4), _translate("MainWindow", "View Playlist"))
        self.radioButton_spotify.setText(_translate("MainWindow", "Spotify"))
        self.label_10.setText(_translate("MainWindow", "DB User"))
        self.label_11.setText(_translate("MainWindow", "DB Pass"))
        self.label_15.setText(_translate("MainWindow", "Proxy Pass"))
        self.pushButton_create_db_table.setText(_translate("MainWindow", "Create DB and Tables"))
        self.label.setText(_translate("MainWindow", "DB IP"))
        self.pushButton_create_demo_playlist.setText(_translate("MainWindow", "Create Demo Playlist"))
        self.radioButton_tidal.setText(_translate("MainWindow", "Tidal"))
        self.label_5.setText(_translate("MainWindow", "DB Port"))
        self.label_14.setText(_translate("MainWindow", "Proxy User"))
        self.label_17.setText(_translate("MainWindow", "Proxy Port"))
        self.column.setTabText(self.column.indexOf(self.tab_3), _translate("MainWindow", "Config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
